---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
- name: centos66
  driver:
    box: centos-6.6 
    vagrantfiles: 
      - Vagrantfile.rb    

suites:
  - name: default
    run_list:
      - role[webserver]
    attributes:
