name             'base'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures base'
long_description 'Installs/Configures base'
version          '0.1.0'

depends 'git', '~> 4.1.0'
depends 'zsh', '~> 1.0.1'
