name             'web_server'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures web_server'
long_description 'Installs/Configures web_server'
version          '0.1.0'

# depends 'users', '~> 1.7.0'
# depends 'sudo', '~> 2.7.1'
depends 'selinux', '~> 0.8.0'
depends 'apache2', '~> 3.0.0'
# depends 'mysql', '~> 6.0.6'
depends 'mysql'
# depends 'mysql', git: 'git://github.com/opscode-cookbooks/mysql.git' 
depends 'database', '~> 2.3.1'
depends 'yum-epel', '~> 0.6.0'
depends 'yum-remi', '~> 0.1.0'
