name             'web_server'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures web_server'
long_description 'Installs/Configures web_server'
version          '0.1.0'

depends 'apache2', '~> 3.0.0'
depends 'mysql', '~> 4.0.0'
depends 'database', '~> 1.6.0'
depends 'yum-epel', '~> 0.6.0'
depends 'yum-remi', '~> 0.1.0'
